pipeline:
  identifier: Build_vagrant_1708538046462
  name: Build vagrant
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1708464582714
        repoName: vagrant
  stages:
    - stage:
        strategy:
          parallelism: 2
        name: test
        identifier: test
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Setup Ruby
                  identifier: setup_ruby
                  spec:
                    uses: ruby/setup-ruby@v1.152.0
                    with:
                      ruby-version: "3.2"
              - step:
                  type: Run
                  name: Dependencies
                  identifier: dependencies
                  spec:
                    shell: Sh
                    command: |-
                      apt-get update -y
                      apt -y install libarchive-tools
              - step:
                  type: RunTests
                  name: Run Tests
                  identifier: run_tests
                  spec:
                    language: Ruby
                    buildTool: Rspec
                    testGlobs: "**/test/unit/**/*_test.rb"
                    runOnlySelectedTests: true
                    enableTestSplitting: true
                    preCommand: bundle install
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotestcoverage
                  name: go_test_coverage
                  spec:
                    command: go test -coverprofile=coverage.out ./...
                  timeout: ""
                  type: Run
              - step:
                  type: RunTests
                  name: Run Ruby Tests
                  identifier: Run_Ruby_Tests
                  spec:
                    language: Ruby
                    buildTool: Rspec
                    runOnlySelectedTests: true
              - step:
                  identifier: gotestreport
                  name: go_test_report
                  spec:
                    command: "export GOBIN=/home/harness/go/bin\n\t\texport PATH=/home/harness/go/bin:$PATH\n\t\techo $PATH\n\t\tgo install github.com/jstemmer/go-junit-report/v2@latest\n\t\tgo test -v 2>&1 ./... | go-junit-report -set-exit-code > report.xml"
                  timeout: ""
                  type: Run
              - step:
                  identifier: bundleinstall
                  name: bundle_install
                  spec:
                    command: bundle install --local || bundle install
                  timeout: ""
                  type: Run
              - step:
                  identifier: rake
                  name: rake
                  spec:
                    command: bundle exec rake
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      password: <+input>
                      repo: hello/world
                      tags: latest
                      username: <+input>
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
